apiVersion: apps/v1
kind: Deployment
metadata:
  name:  proxied-app-deployment
  namespace: default
  labels:
    app:  proxied-app
spec:
  selector:
    matchLabels:
      app: proxied-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  proxied-app
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.23.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 9901
          name: admin
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8081          
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      - name:  nginx
        image:  bitnami/nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  8080
          name:  nginx
        volumeMounts:
        - name: nginx-static-content
          mountPath: /app
      volumes:
        - name: nginx-static-content
          configMap:
            name: nginx-static-content
        - name: envoy-config
          configMap:
            name: envoy-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: proxied-app
  namespace: default
spec:
  selector:
    app: proxied-app
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8081 
    targetPort: 8081
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-static-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      
      <title></title>
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22>
        <text y=%22.9em%22 font-size=%2290%22>
          &#128640;
        </text>
      </svg>">
    </head>
    <body>
      <h1>&#128640;</h1>
    </body>
    </html>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: envoy-config
  namespace: default
data:
  envoy.yaml:  |
    admin:                                                                                                                                          
      address:                                                                                                                                      
        socket_address:                                                                                                                             
          protocol: TCP                                                                                                                             
          address: 0.0.0.0                                                                                                                          
          port_value: 9901
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8081
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: service
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
      - name: service
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8080
    