# kind cluster yaml, one master and three workers

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mesh-kind
nodes:
- role: control-plane
  image: kindest/node:v1.24.3
- role: control-plane
  image: kindest/node:v1.24.3
- role: control-plane
  image: kindest/node:v1.24.3
- role: worker
  image: kindest/node:v1.24.3
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
    protocol: tcp
- role: worker
  image: kindest/node:v1.24.3
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30008
    protocol: tcp
- role: worker
  image: kindest/node:v1.24.3
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30009
    protocol: tcp
